#!/bin/sh

# set up mount directory
echo "Setting up"
sudo rm 2> /dev/null -rf /Volumes/heron_mac
sudo mkdir 2> /dev/null /Volumes/heron_mac

# mount...
echo "Mounting..."
sudo mount_nfs bomb20:/Users/heron /Volumes/heron_mac

exit 0