#!/bin/sh

PWD=`pwd`
REPONAME=`basename ${PWD}`

# git
if 
    test -e .git
then
    echo "Git initialized"
else
    git init
fi

# README.md
if
    test -e README.md
then
    echo "README.md already exists"
else
    echo "# ${REPONAME}" > README.md
fi

# Add files
git add *
git commit -am "Add initial files"
git remote add origin git@github.com:gcasa/${REPONAME}.git
git branch -M main
git push -u origin main

exit $?
