#!/bin/sh

# set up mount directory
echo "Setting up"
# sudo rm 2> /dev/null -rf /Volumes/heron_next
sudo mkdir 2> /dev/null /Volumes/heron_next

# mount...
echo "Mounting..."
sudo mount_nfs -o nolock -o udp -o nfsvers=2 genoa:/Disk1/heron /Volumes/heron_next

exit 0